// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// burteffective
double burteffective(NumericMatrix net, double nactors);
RcppExport SEXP _dream_burteffective(SEXP netSEXP, SEXP nactorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type net(netSEXP);
    Rcpp::traits::input_parameter< double >::type nactors(nactorsSEXP);
    rcpp_result_gen = Rcpp::wrap(burteffective(net, nactors));
    return rcpp_result_gen;
END_RCPP
}
// burtconstraint
double burtconstraint(NumericMatrix net, double nactors);
RcppExport SEXP _dream_burtconstraint(SEXP netSEXP, SEXP nactorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type net(netSEXP);
    Rcpp::traits::input_parameter< double >::type nactors(nactorsSEXP);
    rcpp_result_gen = Rcpp::wrap(burtconstraint(net, nactors));
    return rcpp_result_gen;
END_RCPP
}
// computeREMweightsv1
NumericVector computeREMweightsv1(NumericVector time, NumericVector sampledevent, NumericVector controlevent, CharacterVector dyad_id, double weightScheme, double counts, double cutweight, double halflife);
RcppExport SEXP _dream_computeREMweightsv1(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP dyad_idSEXP, SEXP weightSchemeSEXP, SEXP countsSEXP, SEXP cutweightSEXP, SEXP halflifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dyad_id(dyad_idSEXP);
    Rcpp::traits::input_parameter< double >::type weightScheme(weightSchemeSEXP);
    Rcpp::traits::input_parameter< double >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type cutweight(cutweightSEXP);
    Rcpp::traits::input_parameter< double >::type halflife(halflifeSEXP);
    rcpp_result_gen = Rcpp::wrap(computeREMweightsv1(time, sampledevent, controlevent, dyad_id, weightScheme, counts, cutweight, halflife));
    return rcpp_result_gen;
END_RCPP
}
// computeremweightsv2
NumericVector computeremweightsv2(NumericVector time, NumericVector sampledevent, NumericVector controlevent, CharacterVector dyad_id, CharacterVector dyad_idOpposite, double weightScheme, double counts, double cutweight, double halflife);
RcppExport SEXP _dream_computeremweightsv2(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP dyad_idSEXP, SEXP dyad_idOppositeSEXP, SEXP weightSchemeSEXP, SEXP countsSEXP, SEXP cutweightSEXP, SEXP halflifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dyad_id(dyad_idSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dyad_idOpposite(dyad_idOppositeSEXP);
    Rcpp::traits::input_parameter< double >::type weightScheme(weightSchemeSEXP);
    Rcpp::traits::input_parameter< double >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type cutweight(cutweightSEXP);
    Rcpp::traits::input_parameter< double >::type halflife(halflifeSEXP);
    rcpp_result_gen = Rcpp::wrap(computeremweightsv2(time, sampledevent, controlevent, dyad_id, dyad_idOpposite, weightScheme, counts, cutweight, halflife));
    return rcpp_result_gen;
END_RCPP
}
// computetriadsrem
NumericVector computetriadsrem(NumericVector time, NumericVector sampledevent, NumericVector controlevent, CharacterVector sender, CharacterVector target, CharacterVector dyad_id, double weightScheme, double counts, double cutweight, double halflife, std::string appender, std::string tri_type);
RcppExport SEXP _dream_computetriadsrem(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP dyad_idSEXP, SEXP weightSchemeSEXP, SEXP countsSEXP, SEXP cutweightSEXP, SEXP halflifeSEXP, SEXP appenderSEXP, SEXP tri_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dyad_id(dyad_idSEXP);
    Rcpp::traits::input_parameter< double >::type weightScheme(weightSchemeSEXP);
    Rcpp::traits::input_parameter< double >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type cutweight(cutweightSEXP);
    Rcpp::traits::input_parameter< double >::type halflife(halflifeSEXP);
    Rcpp::traits::input_parameter< std::string >::type appender(appenderSEXP);
    Rcpp::traits::input_parameter< std::string >::type tri_type(tri_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(computetriadsrem(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender, tri_type));
    return rcpp_result_gen;
END_RCPP
}
// extractEventData
std::vector<NumericMatrix> extractEventData(NumericMatrix stats, NumericVector outcome, IntegerVector event_cluster, CharacterVector names);
RcppExport SEXP _dream_extractEventData(SEXP statsSEXP, SEXP outcomeSEXP, SEXP event_clusterSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event_cluster(event_clusterSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(extractEventData(stats, outcome, event_cluster, names));
    return rcpp_result_gen;
END_RCPP
}
// checkVarianceData
NumericVector checkVarianceData(List event_stats, int K);
RcppExport SEXP _dream_checkVarianceData(SEXP event_statsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(checkVarianceData(event_stats, K));
    return rcpp_result_gen;
END_RCPP
}
// pibcpp
NumericVector pibcpp(NumericMatrix net, NumericVector gmem, bool symmetric, std::string traidtype, bool count, double isolate);
RcppExport SEXP _dream_pibcpp(SEXP netSEXP, SEXP gmemSEXP, SEXP symmetricSEXP, SEXP traidtypeSEXP, SEXP countSEXP, SEXP isolateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type net(netSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gmem(gmemSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< std::string >::type traidtype(traidtypeSEXP);
    Rcpp::traits::input_parameter< bool >::type count(countSEXP);
    Rcpp::traits::input_parameter< double >::type isolate(isolateSEXP);
    rcpp_result_gen = Rcpp::wrap(pibcpp(net, gmem, symmetric, traidtype, count, isolate));
    return rcpp_result_gen;
END_RCPP
}
// computerecencynorank
NumericVector computerecencynorank(NumericVector time, NumericVector sampledevent, NumericVector controlevent, std::vector<std::string> dyad_id, std::vector<std::string> sender, std::vector<std::string> target, bool i_neighborhood, bool raw_diff, double nopastEvents, std::string appender);
RcppExport SEXP _dream_computerecencynorank(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP dyad_idSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP i_neighborhoodSEXP, SEXP raw_diffSEXP, SEXP nopastEventsSEXP, SEXP appenderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dyad_id(dyad_idSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type i_neighborhood(i_neighborhoodSEXP);
    Rcpp::traits::input_parameter< bool >::type raw_diff(raw_diffSEXP);
    Rcpp::traits::input_parameter< double >::type nopastEvents(nopastEventsSEXP);
    Rcpp::traits::input_parameter< std::string >::type appender(appenderSEXP);
    rcpp_result_gen = Rcpp::wrap(computerecencynorank(time, sampledevent, controlevent, dyad_id, sender, target, i_neighborhood, raw_diff, nopastEvents, appender));
    return rcpp_result_gen;
END_RCPP
}
// processREMseqOM_varying
List processREMseqOM_varying(std::vector<double> time, std::vector<double> seqid, std::vector<std::string> sender, std::vector<std::string> target, double pobserved, double ncontrols, std::string appender, double rseed);
RcppExport SEXP _dream_processREMseqOM_varying(SEXP timeSEXP, SEXP seqidSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP pobservedSEXP, SEXP ncontrolsSEXP, SEXP appenderSEXP, SEXP rseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type seqid(seqidSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type pobserved(pobservedSEXP);
    Rcpp::traits::input_parameter< double >::type ncontrols(ncontrolsSEXP);
    Rcpp::traits::input_parameter< std::string >::type appender(appenderSEXP);
    Rcpp::traits::input_parameter< double >::type rseed(rseedSEXP);
    rcpp_result_gen = Rcpp::wrap(processREMseqOM_varying(time, seqid, sender, target, pobserved, ncontrols, appender, rseed));
    return rcpp_result_gen;
END_RCPP
}
// persistencerem
NumericVector persistencerem(NumericVector time, NumericVector sampledevent, NumericVector controlevent, std::vector<std::string> dyad_id, std::vector<std::string> actor, bool timedependency, double cuttime, double nopastEvents);
RcppExport SEXP _dream_persistencerem(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP dyad_idSEXP, SEXP actorSEXP, SEXP timedependencySEXP, SEXP cuttimeSEXP, SEXP nopastEventsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dyad_id(dyad_idSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type actor(actorSEXP);
    Rcpp::traits::input_parameter< bool >::type timedependency(timedependencySEXP);
    Rcpp::traits::input_parameter< double >::type cuttime(cuttimeSEXP);
    Rcpp::traits::input_parameter< double >::type nopastEvents(nopastEventsSEXP);
    rcpp_result_gen = Rcpp::wrap(persistencerem(time, sampledevent, controlevent, dyad_id, actor, timedependency, cuttime, nopastEvents));
    return rcpp_result_gen;
END_RCPP
}
// computeremprefattach
NumericVector computeremprefattach(NumericVector sampledevent, NumericVector controlevent, NumericVector time, std::vector<std::string> sender, std::vector<std::string> target);
RcppExport SEXP _dream_computeremprefattach(SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP timeSEXP, SEXP senderSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(computeremprefattach(sampledevent, controlevent, time, sender, target));
    return rcpp_result_gen;
END_RCPP
}
// prefattachrelspanrem
NumericVector prefattachrelspanrem(NumericVector sampledevent, NumericVector controlevent, NumericVector time, std::vector<std::string> sender, std::vector<std::string> target, double reltimespan);
RcppExport SEXP _dream_prefattachrelspanrem(SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP timeSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP reltimespanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type reltimespan(reltimespanSEXP);
    rcpp_result_gen = Rcpp::wrap(prefattachrelspanrem(sampledevent, controlevent, time, sender, target, reltimespan));
    return rcpp_result_gen;
END_RCPP
}
// processREMseqOM
List processREMseqOM(std::vector<double> time, std::vector<double> seqid, std::vector<std::string> sender, std::vector<std::string> target, double pobserved, double ncontrols, double rseed);
RcppExport SEXP _dream_processREMseqOM(SEXP timeSEXP, SEXP seqidSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP pobservedSEXP, SEXP ncontrolsSEXP, SEXP rseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type seqid(seqidSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type pobserved(pobservedSEXP);
    Rcpp::traits::input_parameter< double >::type ncontrols(ncontrolsSEXP);
    Rcpp::traits::input_parameter< double >::type rseed(rseedSEXP);
    rcpp_result_gen = Rcpp::wrap(processREMseqOM(time, seqid, sender, target, pobserved, ncontrols, rseed));
    return rcpp_result_gen;
END_RCPP
}
// processREMseqTM
List processREMseqTM(std::vector<double> time, std::vector<double> seqid, std::vector<std::string> sender, std::vector<std::string> target, double pobserved, double ncontrols, double rseed);
RcppExport SEXP _dream_processREMseqTM(SEXP timeSEXP, SEXP seqidSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP pobservedSEXP, SEXP ncontrolsSEXP, SEXP rseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type seqid(seqidSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type pobserved(pobservedSEXP);
    Rcpp::traits::input_parameter< double >::type ncontrols(ncontrolsSEXP);
    Rcpp::traits::input_parameter< double >::type rseed(rseedSEXP);
    rcpp_result_gen = Rcpp::wrap(processREMseqTM(time, seqid, sender, target, pobserved, ncontrols, rseed));
    return rcpp_result_gen;
END_RCPP
}
// computerecencyrank
NumericVector computerecencyrank(NumericVector time, NumericVector sampledevent, NumericVector controlevent, std::vector<std::string> sender, std::vector<std::string> target, bool i_neighborhood, double nopastEvents, std::string appender);
RcppExport SEXP _dream_computerecencyrank(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP i_neighborhoodSEXP, SEXP nopastEventsSEXP, SEXP appenderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type i_neighborhood(i_neighborhoodSEXP);
    Rcpp::traits::input_parameter< double >::type nopastEvents(nopastEventsSEXP);
    Rcpp::traits::input_parameter< std::string >::type appender(appenderSEXP);
    rcpp_result_gen = Rcpp::wrap(computerecencyrank(time, sampledevent, controlevent, sender, target, i_neighborhood, nopastEvents, appender));
    return rcpp_result_gen;
END_RCPP
}
// remloglike
double remloglike(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remloglike(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remloglike(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// remloglikeOPTIM
double remloglikeOPTIM(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remloglikeOPTIM(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remloglikeOPTIM(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// remGradient
NumericVector remGradient(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remGradient(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remGradient(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// remHessian
NumericMatrix remHessian(NumericVector beta, List event_stats);
RcppExport SEXP _dream_remHessian(SEXP betaSEXP, SEXP event_statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type event_stats(event_statsSEXP);
    rcpp_result_gen = Rcpp::wrap(remHessian(beta, event_stats));
    return rcpp_result_gen;
END_RCPP
}
// computefourcyclesrem
NumericVector computefourcyclesrem(NumericVector time, NumericVector sampledevent, NumericVector controlevent, CharacterVector sender, CharacterVector target, CharacterVector dyad_id, double weightScheme, double counts, double cutweight, double halflife, std::string delim);
RcppExport SEXP _dream_computefourcyclesrem(SEXP timeSEXP, SEXP sampledeventSEXP, SEXP controleventSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP dyad_idSEXP, SEXP weightSchemeSEXP, SEXP countsSEXP, SEXP cutweightSEXP, SEXP halflifeSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sampledevent(sampledeventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type controlevent(controleventSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dyad_id(dyad_idSEXP);
    Rcpp::traits::input_parameter< double >::type weightScheme(weightSchemeSEXP);
    Rcpp::traits::input_parameter< double >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type cutweight(cutweightSEXP);
    Rcpp::traits::input_parameter< double >::type halflife(halflifeSEXP);
    Rcpp::traits::input_parameter< std::string >::type delim(delimSEXP);
    rcpp_result_gen = Rcpp::wrap(computefourcyclesrem(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, delim));
    return rcpp_result_gen;
END_RCPP
}
// tmdegcentraility
NumericVector tmdegcentraility(NumericMatrix tmnet);
RcppExport SEXP _dream_tmdegcentraility(SEXP tmnetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tmnet(tmnetSEXP);
    rcpp_result_gen = Rcpp::wrap(tmdegcentraility(tmnet));
    return rcpp_result_gen;
END_RCPP
}
// tmegodist
NumericVector tmegodist(NumericMatrix net, NumericVector mem);
RcppExport SEXP _dream_tmegodist(SEXP netSEXP, SEXP memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type net(netSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mem(memSEXP);
    rcpp_result_gen = Rcpp::wrap(tmegodist(net, mem));
    return rcpp_result_gen;
END_RCPP
}
// processREMseqTM_varying
List processREMseqTM_varying(std::vector<double> time, std::vector<double> seqid, std::vector<std::string> sender, std::vector<std::string> target, double pobserved, double ncontrols, std::string appender, double rseed);
RcppExport SEXP _dream_processREMseqTM_varying(SEXP timeSEXP, SEXP seqidSEXP, SEXP senderSEXP, SEXP targetSEXP, SEXP pobservedSEXP, SEXP ncontrolsSEXP, SEXP appenderSEXP, SEXP rseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type time(timeSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type seqid(seqidSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type target(targetSEXP);
    Rcpp::traits::input_parameter< double >::type pobserved(pobservedSEXP);
    Rcpp::traits::input_parameter< double >::type ncontrols(ncontrolsSEXP);
    Rcpp::traits::input_parameter< std::string >::type appender(appenderSEXP);
    Rcpp::traits::input_parameter< double >::type rseed(rseedSEXP);
    rcpp_result_gen = Rcpp::wrap(processREMseqTM_varying(time, seqid, sender, target, pobserved, ncontrols, appender, rseed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dream_burteffective", (DL_FUNC) &_dream_burteffective, 2},
    {"_dream_burtconstraint", (DL_FUNC) &_dream_burtconstraint, 2},
    {"_dream_computeREMweightsv1", (DL_FUNC) &_dream_computeREMweightsv1, 8},
    {"_dream_computeremweightsv2", (DL_FUNC) &_dream_computeremweightsv2, 9},
    {"_dream_computetriadsrem", (DL_FUNC) &_dream_computetriadsrem, 12},
    {"_dream_extractEventData", (DL_FUNC) &_dream_extractEventData, 4},
    {"_dream_checkVarianceData", (DL_FUNC) &_dream_checkVarianceData, 2},
    {"_dream_pibcpp", (DL_FUNC) &_dream_pibcpp, 6},
    {"_dream_computerecencynorank", (DL_FUNC) &_dream_computerecencynorank, 10},
    {"_dream_processREMseqOM_varying", (DL_FUNC) &_dream_processREMseqOM_varying, 8},
    {"_dream_persistencerem", (DL_FUNC) &_dream_persistencerem, 8},
    {"_dream_computeremprefattach", (DL_FUNC) &_dream_computeremprefattach, 5},
    {"_dream_prefattachrelspanrem", (DL_FUNC) &_dream_prefattachrelspanrem, 6},
    {"_dream_processREMseqOM", (DL_FUNC) &_dream_processREMseqOM, 7},
    {"_dream_processREMseqTM", (DL_FUNC) &_dream_processREMseqTM, 7},
    {"_dream_computerecencyrank", (DL_FUNC) &_dream_computerecencyrank, 8},
    {"_dream_remloglike", (DL_FUNC) &_dream_remloglike, 2},
    {"_dream_remloglikeOPTIM", (DL_FUNC) &_dream_remloglikeOPTIM, 2},
    {"_dream_remGradient", (DL_FUNC) &_dream_remGradient, 2},
    {"_dream_remHessian", (DL_FUNC) &_dream_remHessian, 2},
    {"_dream_computefourcyclesrem", (DL_FUNC) &_dream_computefourcyclesrem, 11},
    {"_dream_tmdegcentraility", (DL_FUNC) &_dream_tmdegcentraility, 1},
    {"_dream_tmegodist", (DL_FUNC) &_dream_tmegodist, 2},
    {"_dream_processREMseqTM_varying", (DL_FUNC) &_dream_processREMseqTM_varying, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_dream(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
