# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timevaryingomriskset <- function(time, seqid, sender, target, timestart, timeend, actors, pobserved = 1, interval = FALSE, t = 0) {
    .Call(`_dream_timevaryingomriskset`, time, seqid, sender, target, timestart, timeend, actors, pobserved, interval, t)
}

timevaryingtmriskset <- function(time, seqid, sender, target, timestartsender, timeendsenders, actorsenders, timestarttarget, timeendtargets, actortargets, pobserved = 1, interval = FALSE, t = 0) {
    .Call(`_dream_timevaryingtmriskset`, time, seqid, sender, target, timestartsender, timeendsenders, actorsenders, timestarttarget, timeendtargets, actortargets, pobserved, interval, t)
}

timevaryingomrisksetwithsample <- function(time, seqid, sender, target, timestart, timeend, actors, pobserved = 1, ncontrols = 1, appender = "__NIKOACAR3718__", interval = FALSE, t = 0) {
    .Call(`_dream_timevaryingomrisksetwithsample`, time, seqid, sender, target, timestart, timeend, actors, pobserved, ncontrols, appender, interval, t)
}

timevaryingtmrisksetwithsample <- function(time, seqid, sender, target, timestartsender, timeendsenders, actorsenders, timestarttarget, timeendtargets, actortargets, pobserved = 1, ncontrols = 1, appender = "__NIKOACAR3718__", interval = FALSE, t = 0) {
    .Call(`_dream_timevaryingtmrisksetwithsample`, time, seqid, sender, target, timestartsender, timeendsenders, actorsenders, timestarttarget, timeendtargets, actortargets, pobserved, ncontrols, appender, interval, t)
}

burteffective <- function(net, nactors) {
    .Call(`_dream_burteffective`, net, nactors)
}

burtconstraint <- function(net, nactors) {
    .Call(`_dream_burtconstraint`, net, nactors)
}

computeREMweightsv1 <- function(time, sampledevent, controlevent, dyad_id, weightScheme, counts, cutweight, halflife) {
    .Call(`_dream_computeREMweightsv1`, time, sampledevent, controlevent, dyad_id, weightScheme, counts, cutweight, halflife)
}

computeremweightsv2 <- function(time, sampledevent, controlevent, dyad_id, dyad_idOpposite, weightScheme, counts, cutweight, halflife) {
    .Call(`_dream_computeremweightsv2`, time, sampledevent, controlevent, dyad_id, dyad_idOpposite, weightScheme, counts, cutweight, halflife)
}

computetriadsrem <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender, tri_type) {
    .Call(`_dream_computetriadsrem`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender, tri_type)
}

extractEventData <- function(stats, outcome, event_cluster, names) {
    .Call(`_dream_extractEventData`, stats, outcome, event_cluster, names)
}

checkVarianceData <- function(event_stats, K) {
    .Call(`_dream_checkVarianceData`, event_stats, K)
}

fullrisksetom <- function(time, seqid, sender, target, pobserved = 1, interval = FALSE, t = 0) {
    .Call(`_dream_fullrisksetom`, time, seqid, sender, target, pobserved, interval, t)
}

fullrisksettm <- function(time, seqid, sender, target, pobserved = 1, interval = FALSE, t = 0) {
    .Call(`_dream_fullrisksettm`, time, seqid, sender, target, pobserved, interval, t)
}

pibcpp <- function(net, gmem, symmetric, traidtype, count, isolate) {
    .Call(`_dream_pibcpp`, net, gmem, symmetric, traidtype, count, isolate)
}

dream_nodestats <- function(time, time_start, time_end, observed_actor, actor_id, value) {
    .Call(`_dream_dream_nodestats`, time, time_start, time_end, observed_actor, actor_id, value)
}

computerecencynorank <- function(time, sampledevent, controlevent, dyad_id, sender, target, i_neighborhood, raw_diff, nopastEvents, appender) {
    .Call(`_dream_computerecencynorank`, time, sampledevent, controlevent, dyad_id, sender, target, i_neighborhood, raw_diff, nopastEvents, appender)
}

processREMseqOM_varying <- function(time, seqid, sender, target, pobserved = 1, ncontrols = 1, appender = "__NIKOACAR3718__", interval = FALSE, t = 0) {
    .Call(`_dream_processREMseqOM_varying`, time, seqid, sender, target, pobserved, ncontrols, appender, interval, t)
}

persistencerem <- function(time, sampledevent, controlevent, dyad_id, actor, timedependency, cuttime, nopastEvents) {
    .Call(`_dream_persistencerem`, time, sampledevent, controlevent, dyad_id, actor, timedependency, cuttime, nopastEvents)
}

computeremprefattach <- function(sampledevent, controlevent, time, sender, target) {
    .Call(`_dream_computeremprefattach`, sampledevent, controlevent, time, sender, target)
}

prefattachrelspanrem <- function(sampledevent, controlevent, time, sender, target, reltimespan) {
    .Call(`_dream_prefattachrelspanrem`, sampledevent, controlevent, time, sender, target, reltimespan)
}

processREMseqOM <- function(time, seqid, sender, target, pobserved = 1, ncontrols = 1, interval = FALSE, t = 0) {
    .Call(`_dream_processREMseqOM`, time, seqid, sender, target, pobserved, ncontrols, interval, t)
}

processREMseqTM <- function(time, seqid, sender, target, pobserved = 1, ncontrols = 1, interval = FALSE, t = 0) {
    .Call(`_dream_processREMseqTM`, time, seqid, sender, target, pobserved, ncontrols, interval, t)
}

computerecencyrank <- function(time, sampledevent, controlevent, sender, target, i_neighborhood, nopastEvents, appender) {
    .Call(`_dream_computerecencyrank`, time, sampledevent, controlevent, sender, target, i_neighborhood, nopastEvents, appender)
}

remhess_interval <- function(beta, event_stats, interevent, tknown) {
    .Call(`_dream_remhess_interval`, beta, event_stats, interevent, tknown)
}

remgrad_interval <- function(beta, event_stats, interevent, obsindex, tknown) {
    .Call(`_dream_remgrad_interval`, beta, event_stats, interevent, obsindex, tknown)
}

remloglik_interval <- function(beta, event_stats, interevent, obsindex, tknown) {
    .Call(`_dream_remloglik_interval`, beta, event_stats, interevent, obsindex, tknown)
}

remloglik_ordinal <- function(beta, event_stats, obsindex) {
    .Call(`_dream_remloglik_ordinal`, beta, event_stats, obsindex)
}

remgrad_ordinal <- function(beta, event_stats, obsindex) {
    .Call(`_dream_remgrad_ordinal`, beta, event_stats, obsindex)
}

remhess_ordinal <- function(beta, event_stats) {
    .Call(`_dream_remhess_ordinal`, beta, event_stats)
}

computefourcyclesrem <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, delim) {
    .Call(`_dream_computefourcyclesrem`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, delim)
}

tmdegcentraility <- function(tmnet) {
    .Call(`_dream_tmdegcentraility`, tmnet)
}

tmegodist <- function(net, mem) {
    .Call(`_dream_tmegodist`, net, mem)
}

processREMseqTM_varying <- function(time, seqid, sender, target, pobserved = 1, ncontrols = 1, appender = "__NIKOACAR3718__", interval = FALSE, t = 0) {
    .Call(`_dream_processREMseqTM_varying`, time, seqid, sender, target, pobserved, ncontrols, appender, interval, t)
}

