# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

burteffective <- function(net, nactors) {
    .Call(`_dream_burteffective`, net, nactors)
}

burtconstraint <- function(net, nactors) {
    .Call(`_dream_burtconstraint`, net, nactors)
}

computeREMweightsv1 <- function(time, sampledevent, controlevent, dyad_id, weightScheme, counts, cutweight, halflife) {
    .Call(`_dream_computeREMweightsv1`, time, sampledevent, controlevent, dyad_id, weightScheme, counts, cutweight, halflife)
}

computeremweightsv2 <- function(time, sampledevent, controlevent, dyad_id, dyad_idOpposite, weightScheme, counts, cutweight, halflife) {
    .Call(`_dream_computeremweightsv2`, time, sampledevent, controlevent, dyad_id, dyad_idOpposite, weightScheme, counts, cutweight, halflife)
}

computeincomingsharedparts <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender) {
    .Call(`_dream_computeincomingsharedparts`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender)
}

computeincomingtwopaths <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender) {
    .Call(`_dream_computeincomingtwopaths`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender)
}

computeoutsharedpart <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender) {
    .Call(`_dream_computeoutsharedpart`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender)
}

computeouttwopaths <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender) {
    .Call(`_dream_computeouttwopaths`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, appender)
}

extractEventData <- function(stats, outcome, event_cluster, names) {
    .Call(`_dream_extractEventData`, stats, outcome, event_cluster, names)
}

checkVarianceData <- function(event_stats, K) {
    .Call(`_dream_checkVarianceData`, event_stats, K)
}

pibcpp <- function(net, gmem, symmetric, traidtype, count, isolate) {
    .Call(`_dream_pibcpp`, net, gmem, symmetric, traidtype, count, isolate)
}

computerecencynorank <- function(time, sampledevent, controlevent, dyad_id, sender, target, i_neighborhood, raw_diff, nopastEvents, appender) {
    .Call(`_dream_computerecencynorank`, time, sampledevent, controlevent, dyad_id, sender, target, i_neighborhood, raw_diff, nopastEvents, appender)
}

persistencerem <- function(time, sampledevent, controlevent, dyad_id, actor, timedependency, cuttime, nopastEvents) {
    .Call(`_dream_persistencerem`, time, sampledevent, controlevent, dyad_id, actor, timedependency, cuttime, nopastEvents)
}

computeremprefattach <- function(sampledevent, controlevent, time, sender, target) {
    .Call(`_dream_computeremprefattach`, sampledevent, controlevent, time, sender, target)
}

prefattachrelspanrem <- function(sampledevent, controlevent, time, sender, target, reltimespan) {
    .Call(`_dream_prefattachrelspanrem`, sampledevent, controlevent, time, sender, target, reltimespan)
}

processREMseqOM <- function(time, seqid, sender, target, pobserved = 1, ncontrols = 1, rseed = 9999) {
    .Call(`_dream_processREMseqOM`, time, seqid, sender, target, pobserved, ncontrols, rseed)
}

processREMseqTM <- function(time, seqid, sender, target, pobserved = 1, ncontrols = 1, rseed = 9999) {
    .Call(`_dream_processREMseqTM`, time, seqid, sender, target, pobserved, ncontrols, rseed)
}

computerecencyrank <- function(time, sampledevent, controlevent, sender, target, i_neighborhood, nopastEvents, appender) {
    .Call(`_dream_computerecencyrank`, time, sampledevent, controlevent, sender, target, i_neighborhood, nopastEvents, appender)
}

remloglike <- function(beta, event_stats) {
    .Call(`_dream_remloglike`, beta, event_stats)
}

remloglikeOPTIM <- function(beta, event_stats) {
    .Call(`_dream_remloglikeOPTIM`, beta, event_stats)
}

remGradient <- function(beta, event_stats) {
    .Call(`_dream_remGradient`, beta, event_stats)
}

remHessian <- function(beta, event_stats) {
    .Call(`_dream_remHessian`, beta, event_stats)
}

computefourcyclesrem <- function(time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, delim) {
    .Call(`_dream_computefourcyclesrem`, time, sampledevent, controlevent, sender, target, dyad_id, weightScheme, counts, cutweight, halflife, delim)
}

tmdegcentraility <- function(tmnet) {
    .Call(`_dream_tmdegcentraility`, tmnet)
}

tmegodist <- function(net, mem) {
    .Call(`_dream_tmegodist`, net, mem)
}

